name: Compilar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.11.1'

      - name: Descomprimir proyecto
        run: |
          mkdir proyecto
          ZIP=$(find . -maxdepth 1 -name "*.zip" | head -n 1)
          unzip -q "$ZIP" -d proyecto
          sed -i "s/8.10.2/8.10.1/g" proyecto/build.gradle

      - name: Compilar APK
        working-directory: proyecto
        run: gradle :app:assembleDebug --no-daemon

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: PresentacionFotos-debug
          path: proyecto/app/build/outputs/apk/debug/app-debug.apk
